# Generated by Django 3.0.5 on 2020-05-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todos',
            new_name='Item',
        ),
    ]
