# Generated by Django 3.0.5 on 2020-05-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tite',
            new_name='title',
        ),
    ]
